-- ═══════════════════════════════════════════════════════════════════════════
-- MediChain — Phase 0: tenancy, identity, configuration, audit.
--
-- Generated by `prisma migrate diff` from prisma/schema.prisma, then extended
-- by hand with the constraints Prisma's schema language cannot express
-- (partial unique indexes) and the extension the schema depends on (citext).
--
-- Never edit a migration after it has been applied to any environment. A
-- migration is a record of what happened, not a description of what should be
-- true — editing one makes two environments that report the same migration
-- history hold different schemas, which is the hardest kind of drift to find.
-- ═══════════════════════════════════════════════════════════════════════════

-- `citext` backs `user.email`, so that `Admin@Example.com` and
-- `admin@example.com` cannot both register. The comparison is case-insensitive
-- in the database rather than in application code, which means it also holds for
-- a query issued by a script, a migration, or a support tool.
--
-- `pgcrypto` is NOT required: `gen_random_uuid()` has been built into Postgres
-- since 13, and this project targets 17.
CREATE EXTENSION IF NOT EXISTS "citext";

-- CreateEnum
CREATE TYPE "TenantStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'CLOSED');

-- CreateEnum
CREATE TYPE "OrgType" AS ENUM ('DISTRIBUTOR', 'WHOLESALER', 'PHARMACY', 'HOSPITAL');

-- CreateEnum
CREATE TYPE "OrganisationStatus" AS ENUM ('PENDING', 'ACTIVE', 'SUSPENDED', 'BLOCKED');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED');

-- CreateEnum
CREATE TYPE "ActorType" AS ENUM ('USER', 'SYSTEM', 'API_KEY');

-- CreateEnum
CREATE TYPE "SessionRevokedReason" AS ENUM ('LOGOUT', 'ROTATED', 'REUSE_DETECTED', 'ADMIN_FORCED', 'PASSWORD_CHANGED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "OtpPurpose" AS ENUM ('LOGIN', 'REGISTER', 'RESET_PASSWORD', 'VERIFY_CONTACT');

-- CreateEnum
CREATE TYPE "PlatformSettingType" AS ENUM ('STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'SECRET');

-- CreateEnum
CREATE TYPE "AuditOutcome" AS ENUM ('SUCCESS', 'FAILURE');

-- CreateEnum
CREATE TYPE "OutboxStatus" AS ENUM ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED', 'DEAD');

-- CreateTable
CREATE TABLE "tenant" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "code" VARCHAR(32) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "status" "TenantStatus" NOT NULL DEFAULT 'ACTIVE',
    "legal_name" VARCHAR(300),
    "gstin" VARCHAR(15),
    "state_code" VARCHAR(2),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'INR',
    "support_email" VARCHAR(320),
    "support_phone" VARCHAR(20),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "tenant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organisation" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID NOT NULL,
    "type" "OrgType" NOT NULL,
    "status" "OrganisationStatus" NOT NULL DEFAULT 'PENDING',
    "legal_name" VARCHAR(300) NOT NULL,
    "trade_name" VARCHAR(300),
    "drug_licence_no" VARCHAR(64),
    "gstin" VARCHAR(15),
    "pan" VARCHAR(10),
    "state_code" VARCHAR(2),
    "email" VARCHAR(320),
    "phone" VARCHAR(20),
    "payment_terms" VARCHAR(16) NOT NULL DEFAULT 'ADVANCE',
    "credit_limit" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "current_exposure" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "approved_at" TIMESTAMPTZ(6),
    "approved_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "organisation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID,
    "status" "UserStatus" NOT NULL DEFAULT 'PENDING_VERIFICATION',
    "email" CITEXT,
    "phone" VARCHAR(20),
    "full_name" VARCHAR(200) NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "organisation_id" UUID,
    "email_verified_at" TIMESTAMPTZ(6),
    "phone_verified_at" TIMESTAMPTZ(6),
    "failed_login_attempts" INTEGER NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMPTZ(6),
    "last_login_at" TIMESTAMPTZ(6),
    "password_changed_at" TIMESTAMPTZ(6),
    "mfa_enabled" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "role" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID,
    "code" VARCHAR(64) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "description" VARCHAR(500),
    "is_system" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "role_capability" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "role_id" UUID NOT NULL,
    "capability" VARCHAR(64) NOT NULL,

    CONSTRAINT "role_capability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_role" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "role_id" UUID NOT NULL,
    "scope_warehouses" UUID[] DEFAULT ARRAY[]::UUID[],
    "scope_regions" VARCHAR(64)[] DEFAULT ARRAY[]::VARCHAR(64)[],
    "granted_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "device_id" VARCHAR(128),
    "device_label" VARCHAR(200),
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "family_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "last_used_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMPTZ(6),
    "revoked_reason" "SessionRevokedReason",

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refresh_token" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID NOT NULL,
    "session_id" UUID NOT NULL,
    "token_hash" VARCHAR(64) NOT NULL,
    "issued_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "used_at" TIMESTAMPTZ(6),
    "replaced_by_token_id" UUID,

    CONSTRAINT "refresh_token_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "otp_challenge" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID,
    "purpose" "OtpPurpose" NOT NULL,
    "destination" VARCHAR(320) NOT NULL,
    "code_hash" VARCHAR(64) NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 5,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "consumed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" UUID,

    CONSTRAINT "otp_challenge_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform_setting" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" VARCHAR(160) NOT NULL,
    "type" "PlatformSettingType" NOT NULL DEFAULT 'STRING',
    "value" TEXT,
    "encrypted_value" TEXT,
    "description" VARCHAR(500),
    "category" VARCHAR(64) NOT NULL DEFAULT 'general',
    "is_required" BOOLEAN NOT NULL DEFAULT false,
    "version" INTEGER NOT NULL DEFAULT 1,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "platform_setting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "feature_flag" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" VARCHAR(120) NOT NULL,
    "tenant_id" UUID,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "rollout_percentage" INTEGER NOT NULL DEFAULT 0,
    "description" VARCHAR(500),
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "feature_flag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_log" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID NOT NULL,
    "action" VARCHAR(120) NOT NULL,
    "entity" VARCHAR(80),
    "entity_id" UUID,
    "actor_type" "ActorType" NOT NULL,
    "actor_id" UUID,
    "actor_email" VARCHAR(320),
    "actor_role" VARCHAR(64),
    "outcome" "AuditOutcome" NOT NULL DEFAULT 'SUCCESS',
    "correlation_id" VARCHAR(64),
    "request_id" VARCHAR(64),
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "changes" JSONB,
    "metadata" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "outbox_event" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" UUID,
    "event_type" VARCHAR(120) NOT NULL,
    "aggregate_type" VARCHAR(80) NOT NULL,
    "aggregate_id" UUID NOT NULL,
    "payload" JSONB NOT NULL,
    "status" "OutboxStatus" NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 10,
    "locked_at" TIMESTAMPTZ(6),
    "locked_by" VARCHAR(120),
    "last_error" TEXT,
    "published_at" TIMESTAMPTZ(6),
    "deduplication_key" VARCHAR(160),
    "available_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "outbox_event_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "tenant_code_key" ON "tenant"("code");

-- CreateIndex
CREATE INDEX "organisation_tenant_id_status_idx" ON "organisation"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "organisation_tenant_id_type_status_idx" ON "organisation"("tenant_id", "type", "status");

-- CreateIndex
CREATE UNIQUE INDEX "organisation_tenant_id_gstin_key" ON "organisation"("tenant_id", "gstin");

-- CreateIndex
CREATE INDEX "user_tenant_id_status_idx" ON "user"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "user_email_idx" ON "user"("email");

-- CreateIndex
CREATE INDEX "user_phone_idx" ON "user"("phone");

-- CreateIndex
CREATE INDEX "role_tenant_id_code_idx" ON "role"("tenant_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "role_capability_role_id_capability_key" ON "role_capability"("role_id", "capability");

-- CreateIndex
CREATE INDEX "user_role_user_id_idx" ON "user_role"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "user_role_user_id_role_id_key" ON "user_role"("user_id", "role_id");

-- CreateIndex
CREATE INDEX "session_user_id_revoked_at_idx" ON "session"("user_id", "revoked_at");

-- CreateIndex
CREATE INDEX "session_family_id_idx" ON "session"("family_id");

-- CreateIndex
CREATE INDEX "session_expires_at_idx" ON "session"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_token_token_hash_key" ON "refresh_token"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_token_session_id_idx" ON "refresh_token"("session_id");

-- CreateIndex
CREATE INDEX "refresh_token_tenant_id_expires_at_idx" ON "refresh_token"("tenant_id", "expires_at");

-- CreateIndex
CREATE INDEX "otp_challenge_destination_purpose_consumed_at_idx" ON "otp_challenge"("destination", "purpose", "consumed_at");

-- CreateIndex
CREATE INDEX "otp_challenge_expires_at_idx" ON "otp_challenge"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "platform_setting_key_key" ON "platform_setting"("key");

-- CreateIndex
CREATE INDEX "platform_setting_category_idx" ON "platform_setting"("category");

-- CreateIndex
CREATE INDEX "feature_flag_key_tenant_id_idx" ON "feature_flag"("key", "tenant_id");

-- CreateIndex
CREATE INDEX "audit_log_tenant_id_created_at_idx" ON "audit_log"("tenant_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_log_tenant_id_entity_entity_id_idx" ON "audit_log"("tenant_id", "entity", "entity_id");

-- CreateIndex
CREATE INDEX "audit_log_tenant_id_actor_id_created_at_idx" ON "audit_log"("tenant_id", "actor_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_log_correlation_id_idx" ON "audit_log"("correlation_id");

-- CreateIndex
CREATE INDEX "outbox_event_status_available_at_idx" ON "outbox_event"("status", "available_at");

-- CreateIndex
CREATE INDEX "outbox_event_aggregate_type_aggregate_id_created_at_idx" ON "outbox_event"("aggregate_type", "aggregate_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "outbox_event_deduplication_key_key" ON "outbox_event"("deduplication_key");

-- AddForeignKey
ALTER TABLE "organisation" ADD CONSTRAINT "organisation_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user" ADD CONSTRAINT "user_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user" ADD CONSTRAINT "user_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "role" ADD CONSTRAINT "role_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "role_capability" ADD CONSTRAINT "role_capability_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_token" ADD CONSTRAINT "refresh_token_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "otp_challenge" ADD CONSTRAINT "otp_challenge_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ═══════════════════════════════════════════════════════════════════════════
-- Constraints Prisma's schema language cannot express.
--
-- Prisma has no syntax for a partial index, and a plain `@@unique` is not a
-- substitute for any of the four cases below.
-- ═══════════════════════════════════════════════════════════════════════════

-- One account per email address per tenant, among live rows only.
--
-- Two things make this partial. First, `tenant_id` is in the key: two pharma
-- companies may legitimately both sell to the same pharmacy, and that pharmacy
-- may hold an account with each. Second, `deleted_at IS NULL` is in the
-- predicate: a soft-deleted account must not block the address from being
-- re-registered, which is what a plain unique index would do.
CREATE UNIQUE INDEX "user_tenant_email_active_key"
  ON "user" ("tenant_id", "email")
  WHERE "deleted_at" IS NULL AND "email" IS NOT NULL;

-- The same rule for phone numbers, which are an alternative sign-in identifier.
CREATE UNIQUE INDEX "user_tenant_phone_active_key"
  ON "user" ("tenant_id", "phone")
  WHERE "deleted_at" IS NULL AND "phone" IS NOT NULL;

-- Role codes are unique per tenant — and separately unique for the seeded
-- global roles, whose `tenant_id` is NULL.
--
-- A plain `@@unique([tenantId, code])` does not achieve this: Postgres treats
-- NULLs as distinct, so it would permit unlimited rows with `tenant_id = NULL`
-- and the same code. Two partial indexes express the intended rule exactly.
CREATE UNIQUE INDEX "role_tenant_code_key"
  ON "role" ("tenant_id", "code")
  WHERE "tenant_id" IS NOT NULL;

CREATE UNIQUE INDEX "role_global_code_key"
  ON "role" ("code")
  WHERE "tenant_id" IS NULL;

-- Feature flags follow the same pattern: a tenant may override a platform
-- default, but may not define the same key twice.
CREATE UNIQUE INDEX "feature_flag_tenant_key"
  ON "feature_flag" ("key", "tenant_id")
  WHERE "tenant_id" IS NOT NULL;

CREATE UNIQUE INDEX "feature_flag_global_key"
  ON "feature_flag" ("key")
  WHERE "tenant_id" IS NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- Make the audit log append-only at the database level.
--
-- The application has no update or delete path for this table, but a rule that
-- lives only in application code is a rule that a future migration, a support
-- script or a `psql` session can break without anyone noticing. An audit trail
-- that can be rewritten is not evidence, so the restriction is enforced where it
-- cannot be bypassed.
--
-- Mechanism: TRIGGERS, not GRANTs.
--
-- A `REVOKE UPDATE, DELETE ON audit_log FROM <role>` is the obvious approach and
-- it does not work. PostgreSQL gives a table's owner an implicit grant that
-- cannot be revoked — so if the application connects as the owner (the common
-- case, and what DATABASE_URL in .env.example implies), the revoke succeeds,
-- prints nothing alarming, and protects nothing. Worse, a migration that runs as
-- a *separate* migration role would revoke from itself rather than from the
-- application role, so it would also protect nothing while looking correct.
--
-- A BEFORE UPDATE/DELETE trigger that raises is owned by the migration role and
-- fires regardless of who holds the table privilege. The owner can still drop
-- the trigger, but that is a deliberate DDL act recorded in the schema, whereas
-- a missing grant is invisible.
--
-- TRUNCATE needs its own statement-level trigger: a row-level trigger never sees
-- it. Both are covered.
--
-- Escape hatch: retention purges and test fixtures set
--   SET LOCAL medichain.allow_audit_mutation = 'on';
-- for the duration of one transaction. Deliberate, greppable, and scoped to a
-- transaction rather than a session, so it cannot leak into request handling.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION "audit_log_reject_mutation"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- `true` as the second argument to current_setting means "return NULL if
  -- unset" instead of raising. An unset GUC is the normal case.
  IF current_setting('medichain.allow_audit_mutation', true) = 'on' THEN
    -- NEW is NULL on DELETE, OLD is NULL on UPDATE; COALESCE picks whichever
    -- exists so the row is passed through unchanged.
    RETURN COALESCE(NEW, OLD);
  END IF;

  RAISE EXCEPTION
    'audit_log is append-only: % is not permitted', TG_OP
    USING
      ERRCODE = 'restrict_violation',
      HINT = 'An audit trail that can be rewritten is not evidence. If this is a retention purge or a test fixture, wrap it in a transaction that sets: SET LOCAL medichain.allow_audit_mutation = ''on'';';
END;
$$;

CREATE TRIGGER "audit_log_no_row_mutation"
  BEFORE UPDATE OR DELETE ON "audit_log"
  FOR EACH ROW
  EXECUTE FUNCTION "audit_log_reject_mutation"();

CREATE TRIGGER "audit_log_no_truncate"
  BEFORE TRUNCATE ON "audit_log"
  FOR EACH STATEMENT
  EXECUTE FUNCTION "audit_log_reject_mutation"();

-- Defence in depth for the multi-role setup: if a future migration ever grants
-- table privileges to PUBLIC, this closes it. It is not the primary mechanism —
-- see the comment above for why a grant-based approach cannot be relied on.
REVOKE UPDATE, DELETE, TRUNCATE ON "audit_log" FROM PUBLIC;

-- Report the state honestly rather than claiming protection that may not apply.
DO $$
DECLARE
  owner_role text;
BEGIN
  SELECT pg_catalog.pg_get_userbyid(c.relowner) INTO owner_role
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relname = 'audit_log' AND n.nspname = current_schema();

  IF owner_role = current_user THEN
    RAISE NOTICE
      'audit_log is append-only via triggers. NOTE: the current role (%) owns the table, so it can drop the trigger. For defence in depth in production, run migrations as a separate owner role and grant the application role only INSERT, SELECT on audit_log.',
      current_user;
  ELSE
    RAISE NOTICE
      'audit_log is append-only via triggers for role % (table owner: %).', current_user, owner_role;
  END IF;
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE NOTICE
      'audit_log triggers created, but the REVOKE was skipped: insufficient privilege.';
END $$;
